spring:
  application:
    name: currency-rates
  datasource:
    url: jdbc:h2:mem:currency_rates
    username: root
  h2:
    console.enabled: true
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
      order_inserts: true

external_api:
  url: https://api.nbrb.by

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /api-docs.yaml